### ISSUE TITLE
Youtube controls hidden with autoplay

### ISSUE THREAD

**Issue by wplit** [vime-js/vime#111]
I see that with autoplay on, the youtube player won't show the UI controls, they are hidden, and if he opacity is manually changed so they are visible, they no longer work. Is this a bug or is it that youtube doesn't allow the controls to work if the video is on autoplay?

**Comment by mihar-22** [comment]
It should work... If you're using the native YouTube controls then have you set the `controls` property on `vime-player`?

**Comment by wplit** [comment]
I mean with the non-native controls, the video controls are hidden, the video doesn't play and if I manually inspect to make the controls visible, they don't work. This is only with autoplay on. It actually happens with vimeo and youtube..

https://wplit.com/vime-youtube-autoplay/

**Comment by wplit** [comment]
I know this was closed, but I'm still having issues with autoplay. It's on with vime-video that I'm seeing the expected result, and that's only sometimes. see my demo page again, this time with just autoplay on. I muted as well as I read in the docs it's more likely to work with mute on.

https://wplit.com/vime-youtube-autoplay/

**Comment by mihar-22** [comment]
I just released another fix, hopefully that helps. Autoplay is always very hit or miss in my experience.

**Comment by mihar-22** [comment]
Whenever you get a chance to test it, if could let me know if it's resolved or not would be awesome @wplit.

**Comment by wplit** [comment]
I was still getting the same issue. 

I think this has more to do with the fact that the play() can't be done programmatically (needs user interaction)

I checked canAutoplay() and canMutedAutoplay() and everything was showing true.

Then i removed autoplay from the player and created my own (using intersectionObserver to use play() as the players come into view when the are ready, the exact same issue happened. play() only seems to work on a click event, it won't work on anything scroll related. 

You probably knew all this part, but just letting you know.. it's the same issue using the 'autoplay' property that you have in the player, or trying to recreate it manually to get play() to work.

**Comment by wplit** [comment]
Update: I found the issue (i think). 

It comes from another issue, that when using the vime-youtube, when adding the muted attribute to the vime-player, it doesn't actually get passed down to youtube onto the src attr and therefore mute=0 is always added to the iframe code. This needs to be mute=1. And browsers don't like autoplay if mute isn't on.

i tested by just pulling out the iframe code that is output by the player, changing the mute=0 to mute=1 in the src and it autoplays without issue.

Here you can see in the source code, the muted and autoplay are added to the vime-player, but only the autoplay=1 gets added to the iframe output, not the muted=1

<img width="1485" alt="Screen Shot 2020-11-20 at 11 56 45 am" src="https://user-images.githubusercontent.com/43051571/99742531-cabc7780-2b27-11eb-8a0d-671b4539d927.png">

live eg https://wplit.com/vime-youtube-autoplay/

**Comment by szczepankosmowski** [comment]
This seems to be the same issue as I'm having with vimeo autoplay: https://github.com/vime-js/vime/issues/127

The muted attributed in the vime-player component is not actually being passed through to the embed source url parameters.

> Update: I found the issue (i think).
> 
> It comes from another issue, that when using the vime-youtube, when adding the muted attribute to the vime-player, it doesn't actually get passed down to youtube onto the src attr and therefore mute=0 is always added to the iframe code. This needs to be mute=1. And browsers don't like autoplay if mute isn't on, sometimes it may work, but often it doesn't.
> 
> i tested by just pulling out the iframe code that is output by the player, changing the mute=0 to mute=1 in the src and it autoplays without issue.
> 
> Here you can see in the source code, the muted and autoplay are added to the vime-player, but only the autoplay=1 gets added to the iframe output, not the muted=1
> 
> <img alt="Screen Shot 2020-11-20 at 11 56 45 am" width="1485" src="https://user-images.githubusercontent.com/43051571/99742531-cabc7780-2b27-11eb-8a0d-671b4539d927.png">
> 
> live eg https://wplit.com/vime-youtube-autoplay/

**Comment by ViacheslavBurlaka** [comment]
on mobile safari problem with autoplay too

**Comment by jmtalves** [comment]
@mihar-22  is not resolve. muted keep zero
