### ISSUE TITLE
Not working with Angular 9

### ISSUE THREAD

**Issue by MoroccanGeek** [vime-js/vime#124]
I'm using Angular V9.1.11, and i tried to use the latest version of vime but it gives an error as you can see below : 

Compiling @vime/angular : module as esm5
Warning: Invalid constructor parameter decorator in D:/Projects/My Project/My-Project/node_modules/@vime/angular/dist/fesm2015/vime-angular.js:
 () => [
    { type: ChangeDetectorRef },
    { type: ElementRef },
    { type: NgZone }
]
Error: Error on worker #1: Error: getInternalNameOfClass() called on a non-ES5 class: expected VimeAudio to have an inner class declaration
    at Esm5ReflectionHost.getInternalNameOfClass (D:\Projects\My Project\My-Project\node_modules\@angular\compiler-cli\ngcc\src\host\esm5_host.js:88:23)
    at DelegatingReflectionHost.getInternalNameOfClass (D:\Projects\My Project\My-Project\node_modules\@angular\compiler-cli\ngcc\src\host\delegating_host.js:89:34)
    at Object.extractDirectiveMetadata (D:\Projects\My Project\My-Project\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\directive.js:237:69)
    at ComponentDecoratorHandler.analyze (D:\Projects\My Project\My-Project\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:143:47)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (D:\Projects\My Project\My-Project\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:345:40)
    at analyze (D:\Projects\My Project\My-Project\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:297:58)
    at _loop_1 (D:\Projects\My Project\My-Project\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:319:21)
    at NgccTraitCompiler.TraitCompiler.analyzeClass (D:\Projects\My Project\My-Project\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:325:35)
    at NgccTraitCompiler.analyzeFile (D:\Projects\My Project\My-Project\node_modules\@angular\compiler-cli\ngcc\src\analysis\ngcc_trait_compiler.js:47:26)
    at DecorationAnalyzer.analyzeProgram (D:\Projects\My Project\My-Project\node_modules\@angular\compiler-cli\ngcc\src\analysis\decoration_analyzer.js:134:39)
    at ClusterMaster.onWorkerMessage (D:\Projects\My Project\My-Project\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:194:27)
    at D:\Projects\My Project\My-Project\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:54:95
    at ClusterMaster.<anonymous> (D:\Projects\My Project\My-Project\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:292:57)
    at step (D:\Projects\My Project\My-Project\node_modules\tslib\tslib.js:140:27)
    at Object.next (D:\Projects\My Project\My-Project\node_modules\tslib\tslib.js:121:57)
    at D:\Projects\My Project\My-Project\node_modules\tslib\tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (D:\Projects\My Project\My-Project\node_modules\tslib\tslib.js:110:16)
    at EventEmitter.<anonymous> (D:\Projects\My Project\My-Project\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:286:32)
    at EventEmitter.emit (events.js:314:20)
An unhandled exception occurred: NGCC failed.
See "C:\Users\saber\AppData\Local\Temp\ng-KmWmwL\angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file C:\Windows\system32\cmd.exe
npm ERR! errno ENOENT
npm ERR! angular-electron@7.2.1 ng:serve: `ng serve`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the angular-electron@7.2.1 ng:serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\saber\AppData\Roaming\npm-cache\_logs\2020-11-30T14_36_06_880Z-debug.log
ERROR: "ng:serve" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-electron@7.2.1 start: `npm-run-all -p electron:serve ng:serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-electron@7.2.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\saber\AppData\Roaming\npm-cache\_logs\2020-11-30T14_36_06_999Z-debug.log

I've tried version 4.2.2 just to see if things gonna work, but nothing

**Comment by jnurse13** [comment]
No improvement with 5.0.8 - can test in dev, but doesn't play nicely with Ivy for a prod build.

**Comment by mihar-22** [comment]
Ah damn. Okay it's no problem because I'll be building a proper development workflow for testing framework integrations after the weekend (first thing Monday, Saturday now). I'll spot all the bugs and fix it up then.

**Comment by michalhornak22** [comment]
I have similar issue with angular 10, my prod build runs allright, but all vime videos in prod builds or prod serve wont work...but in dev build everything works fine...i have used v 4.7.3 which worked all right until few days ago, Im guessing it could also be some chrome update which started doing this error, because the same error is on 4.7.3 and also on all v5 versions.. you can see my usage of vime videos here: http://ikony-doc.michalhornak.me/#/chapter1 there is no height on videos and if you click play it crashes..I tried to use last week versioin of my app which worked 100% and still not working now...

**Comment by michalhornak22** [comment]
i have tried same thing with your angular example https://github.com/vime-js/vime/tree/master/examples/angular. with ng serve everything works fine, but ng serve --prod has same problem as my app...

**Comment by mihar-22** [comment]
Okay so this is working in production on my end with Angular 11. It seems like I needed to compile the library down to `es5`. I don't have the time to test Angular 9/10, once the release is out (green tick on commit above this comment), then please let me know if the issue is resolved 🤞

**Comment by michalhornak22** [comment]
I tested it with 5.0.14 and 5.0.15 on angular 10 example https://github.com/vime-js/vime/tree/master/examples/angular but with no change...

**Comment by mihar-22** [comment]
Is there any significant difference between Angular 10 and 11 that would prevent it from working? I'm just not seeing what the problem is.

**Comment by MoroccanGeek** [comment]
> I tested it with 5.0.14 and 5.0.15 on angular 10 example https://github.com/vime-js/vime/tree/master/examples/angular but with no change...

It would be helpful if you can upload a video (Just a suggestion)

**Comment by jnurse13** [comment]
So on prod Web-components not getting 'hydrated' not sure if that is the right term!
see image 
![Screenshot 2020-12-21 at 10 22 40](https://user-images.githubusercontent.com/1510691/102766902-bd88e780-4376-11eb-8198-2f0e7f6e2dab.png)

ignore the fact I have tried to use a custom playbutton incorrectly - it was doing the same before that.

This is with 9.1.0

see you have these dependencies listed -
requires a peer of @angular/common@^11.0.4 but none is installed. You must install peer dependencies yourself.
npm WARN @vime/angular@5.0.15 requires a peer of @angular/core@^11.0.4 but none is installed. You must install peer dependencies yourself.
npm WARN @vime/angular@5.0.15 requires a peer of rxjs@^6.6.2 but none is installed. You must install peer dependencies yourself.

**Comment by jnurse13** [comment]
> So on prod Web-components not getting 'hydrated' not sure if that is the right term!
> see image
> ![Screenshot 2020-12-21 at 10 22 40](https://user-images.githubusercontent.com/1510691/102766902-bd88e780-4376-11eb-8198-2f0e7f6e2dab.png)
> 
> ignore the fact I have tried to use a custom playbutton incorrectly - it was doing the same before that.
> 
> This is with 9.1.0
> 
> see you have these dependencies listed -
> requires a peer of @angular/common@^11.0.4 but none is installed. You must install peer dependencies yourself.
> npm WARN @vime/angular@5.0.15 requires a peer of @angular/core@^11.0.4 but none is installed. You must install peer dependencies yourself.
> npm WARN @vime/angular@5.0.15 requires a peer of rxjs@^6.6.2 but none is installed. You must install peer dependencies yourself.

Bumping to 5.0.16 that you released 9 minutes and will update you

**Comment by mihar-22** [comment]
Angular 10 is resolved. I haven't tested Angular 9 but I'm releasing 5.0.17 that might also help.

**Comment by mihar-22** [comment]
I fixed web components not being registered in `5.0.16`.

**Comment by jnurse13** [comment]
on 5.0.16 still get these warnings 

npm WARN @vime/angular@5.0.16 requires a peer of @angular/common@^11.0.4 but none is installed. You must install peer dependencies yourself.
npm WARN @vime/angular@5.0.16 requires a peer of @angular/core@^11.0.4 but none is installed. You must install peer dependencies yourself.
npm WARN @vime/angular@5.0.16 requires a peer of rxjs@^6.6.2 but none is installed. You must install peer dependencies yourself.

and this on build

Warning: Entry point '@vime/angular' contains deep imports into '....@vime/core/dist/types'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

But .... otherwise AWESOME working with angular 9.1.0 - prod build - that was using 5.0.16

Thank you

**Comment by mihar-22** [comment]
Okay I'm going to revert `5.0.17`, seems useless. Really glad it's all working now 😄

**Comment by michalhornak22** [comment]
up and running, thx very much :)
